### ISSUE TITLE
指定アドレスのメモリを読みたい

### ISSUE THREAD

**Issue by GB19xx** [TamanegiMage/FFXIV_MemoryReader#13]
TamanegiMage 様

主題のとおり
機能追加は可能でしょうか？

> FFXIV_MemoryReader.Core.Memory.GetByteArray()

雰囲気コード
```
IntPrt address = 0xABC123;

// 指定アドレスから20バイト読み込み
byte[] data = memoryPlugin?.Read(address, 20);

// 任意の処理
....
```

**Comment by TamanegiMage** [comment]
https://github.com/TamanegiMage/FFXIV_MemoryReader/blob/5ae71b5246cbfab06a2f6e84ebac797c8c4b23c1/FFXIV_MemoryReader.Core/MemoryScanner.cs#L350

これを使いたいという意味でしょうか。

**Comment by TamanegiMage** [comment]
プロセスと読みたいアドレスが分かっているなら、
`kernel32.dll` を使って `ReadProcessMemory` で読めばいいです。
あえて FFXIV_MemoryReader を使う必要がありません。

**Comment by GB19xx** [comment]
分かりました
